name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      server_ip:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_key:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ inputs.server_ip }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        script: |
          mkdir -p ~/github-deployment
          rm -rf ~/github-deployment/*
          exit
    
    - name: Copy Files to Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ inputs.server_ip }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        source: .
        target: ~/github-deployment
