name: AWS Deploy Workflow

on:
  workflow_call:
    inputs:
      source:
        required: false
        type: string
        default: "." # Default to copying everything from the repository root
      target:
        required: true
        type: string
    secrets:
      AWS_PRIVATE_KEY:
        required: true
      AWS_IP:
        required: true
      AWS_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Copy files to the server
      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.AWS_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: ${{ inputs.source }}
          target: ${{ inputs.target }}
