name: Reusable Workflow

on:
  workflow_call:  # This allows this workflow to be called by other workflows

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"
